In [5]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold, RandomizedSearchCV
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, f1_score, make_scorer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer
import time

from sklearn.utils._testing import ignore_warnings
from sklearn.exceptions import ConvergenceWarning

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, StandardScaler, RobustScaler, PowerTransformer, OneHotEncoder, PolynomialFeatures, FunctionTransformer, QuantileTransformer



from imblearn.over_sampling import SMOTE, ADASYN, BorderlineSMOTE
from imblearn.under_sampling import RandomUnderSampler, TomekLinks
from imblearn.combine import SMOTETomek
from imblearn.pipeline import Pipeline as ImbPipeline

from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

#from tensorflow.keras.utils import plot_model

#import plotly.graph_objects as go
import plotly.express as px
#import plotly.io as pio
import duckdb
from sklearn.model_selection import train_test_split
import math
#import warnings

import tensorflow as tf


#pio.templates.default = "seaborn"

#pio.templates["custom_theme"] = go.layout.Template(
#    layout=go.Layout(
#        #paper_bgcolor='rgba(0,0,0,0)', 
#        plot_bgcolor="rgba(230,230,230,255)",
#
#        colorway=px.colors.qualitative.D3
#
#    )
#)

#pio.templates.default = 'custom_theme'

lab_dict = {
        "udi":"UDI",
        "product_id":"Product ID",
        "type":"Type",
        "air_temperature_k":"Air temperature [K]",
        'process_temperature_k':'Process temperature [K]',
        'rotational_speed_rpm':'Rotational speed [RPM]',
        'torque_nm':'Torque [Nm]',
        'tool_wear_min':'Tool wear [min]',
        "machine_failure":"Machine failure",
        "twf":"Tool Wear Failure",
        "hdf":"Heat Dissipation  Failure",
        "pwf":"Power Failure",
        "osf":"Over Strain Failure",
        "rnf":"Random Failure",
        "delta_temp_k": "Temperature Difference [K]",
        "power_w":"Power [kW]",
        "cons_number":"#Product",
        "wear_torque":"Tool Wear [min] x Torque [Nm] "
        }

In [ ]:
def load_data(incl_cols, target):

    with duckdb.connect("data/team_data.duckdb") as conn:
        df = conn.execute("SELECT * FROM ai4i2020").fetchdf()

    df_features = df
    df_features.columns = df_features.columns.str.lower().str.replace(" ","_").str.replace("[","").str.replace("]","")

    

    # generate additional columns
    # power measured in W = 1Nm/s // torque in Nm // rotational speed in rpm => * 60 (sec) / 2pi (one ration)
    df_features["power_w"] = (df_features["torque_nm"] / (df_features["rotational_speed_rpm"] * 60 / (2 * math.pi))) * 1000
    df_features["delta_temp_k"] = df_features["process_temperature_k"]-df_features["air_temperature_k"]
    df_features["wear_torque"]  = df_features["tool_wear_min"]*df_features["torque_nm"]
    
    # set categorical columns
    target_cols =[
        "machine_failure",
        "twf",
        "hdf",
        "pwf",
        "osf",
        "rnf"
        ]

    for col in target_cols:
        df_features[col] = df_features[col].astype("category")


    cols = incl_cols.copy()
    cols.append(target)
    df_output = df_features[cols]
    
    return df_output

In [ ]:
df = load_data(target = "machine_failure",incl_cols=['type','air_temperature_k','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k','wear_torque'],)
for col in ['air_temperature_k','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k','wear_torque']:
    print(f"st.slider(label='{lab_dict[col]}', min_value={int(df[col].min())}, max_value={int(df[col].max())}, value={int(df[col].min()+((df[col].max()-df[col].min())/2))} , step=1 , key='{col}')")

st.slider(label='Air temperature [K]', min_value=295, max_value=304, value=309 , step=1 , key='air_temperature_k')
st.slider(label='Process temperature [K]', min_value=305, max_value=313, value=317 , step=1 , key='process_temperature_k')
st.slider(label='Rotational speed [RPM]', min_value=1168, max_value=2886, value=3745 , step=1 , key='rotational_speed_rpm')
st.slider(label='Torque [Nm]', min_value=3, max_value=76, value=113 , step=1 , key='torque_nm')
st.slider(label='Tool wear [min]', min_value=0, max_value=253, value=379 , step=1 , key='tool_wear_min')
st.slider(label='Power [kW]', min_value=0, max_value=6, value=9 , step=1 , key='power_w')
st.slider(label='Temperature Difference [K]', min_value=7, max_value=12, value=14 , step=1 , key='delta_temp_k')
st.slider(label='Tool Wear [min] x Torque [Nm] ', min_value=0, max_value=16497, value=24745 , step=1 , key='wear_torque')

In [5]:
def split_data(dataframe, stratify, target="machine_failure",seed=42):
    

    y = dataframe[target]
    X = dataframe.drop(target, axis=1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=seed,stratify=stratify )

    return  X_train, X_test, y_train, y_test

In [6]:
@ignore_warnings(category=ConvergenceWarning)

def train_with_aggressive_weights(X_train, y_train, scaler, approach_key, approach_input, categorical_features, hidden_layer_sizes, alpha,learning_rate_init, batch_size, activation, solver):
    
    classes = np.unique(y_train)
    minority_class = classes[np.argmin(np.bincount(y_train))]


    # apply class weights
    if approach_key == "class_weights":
        # Compute and amplify class weights
        weights = compute_class_weight('balanced', classes=classes, y=y_train)
    
        # Amplify minority class weight by 1.5x
        class_weights = dict(zip(classes, weights))
        class_weights[minority_class] *= approach_input
        sample_weights = np.array([class_weights[c] for c in y_train])
    
    numerical_features = X_train.select_dtypes(include=np.number).columns.tolist()

    preprocess = ColumnTransformer(transformers=[    
        ("encode_cats", OrdinalEncoder(), categorical_features),
        ("scale", scaler, numerical_features)
        ],remainder="drop")



    mlp = MLPClassifier(
        hidden_layer_sizes=hidden_layer_sizes,
        activation=activation,
        solver=solver,
        alpha=alpha,
        batch_size=batch_size,
        learning_rate='adaptive',
        learning_rate_init=learning_rate_init,
        max_iter=1500,
        early_stopping=True,
        validation_fraction=0.15,
        n_iter_no_change=30,
        random_state=42,
        verbose=0
    )


    if approach_key == "class_weights":
        pipeline = Pipeline(steps=[
            ('preprocess', preprocess),
            ('model', mlp),
        ])
    if approach_key == "resampling":
        
    # apply resampling approaches
    
        if approach_input=="ADASYN":
            pipeline = ImbPipeline(steps=[
            ('preprocess', preprocess),
            ("over", ADASYN(random_state=42)),
            ("under",  TomekLinks()),
            ('model', mlp),
            ])
            
        if approach_input=="SMOTETomek":
            pipeline = ImbPipeline(steps=[
            ('preprocess', preprocess),
            ("over_under", SMOTETomek( random_state=42)),
            ('model', mlp),
            ])


    if approach_key == "class_weights":
        pipeline.fit(X_train, y_train, model__sample_weight=sample_weights)
    if approach_key == "resampling":
        pipeline.fit(X_train, y_train)
    

    return pipeline, pipeline.get_params()

In [7]:
def optimize_threshold(model, X_train, y_train, scaler=None):
    """
    Find optimal decision threshold to maximize F1 for minority class
    """
    
    y_proba = model.predict_proba(X_train)[:, 1]
    
    # Try different thresholds
    thresholds = np.arange(0.01, 0.90, 0.01)
    best_f1 = 0
    best_threshold = 0.5
    
    minority_class = np.argmin(np.bincount(y_train))
    
    for threshold in thresholds:
        y_pred_temp = (y_proba >= threshold).astype(int)
        f1 = f1_score(y_train, y_pred_temp, pos_label=minority_class)
        if f1 > best_f1:
            best_f1 = f1
            best_threshold = threshold
    
    #print(f"Optimal threshold: {best_threshold:.2f} with F1: {best_f1:.4f}")
    return best_threshold

In [8]:
def predict_with_threshold(model, X, threshold=0.5):
    """
    Make predictions using custom threshold
    """
    
    y_proba = model.predict_proba(X)[:, 1]
    
    return (y_proba >= threshold).astype(int)

In [9]:
def report_progress(runs, i, duration, total_duration, f1_result):
    progress = round((i/runs)*100,1)
    if progress == 0:
        feedback = f"process with {runs} runs started at {time.ctime(time.time())}"
    elif progress == 100:
        feedback = f"process with {runs} runs completed in {round(total_duration/60,1)}min at {time.ctime(time.time())}"
    else:
        remaining = round((((100/progress)*total_duration)-total_duration)/60,1)
        feedback = f"progress: {progress}%  |  remaining: {remaining}min   |  elapsed: {round(total_duration/60,1)}min  |   loop duration: {round(duration/60,1)}min    |   best f1: {f1_result}"
    
    return feedback

In [20]:
target = "machine_failure"
categorical_feature = ["type"]
column_selection = {
    "none" : ['type','air_temperature_k','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k','wear_torque'],
    "rem" : ['type','process_temperature_k','rotational_speed_rpm','tool_wear_min','power_w','delta_temp_k','wear_torque'],

    #"type" : ['air_temperature_k','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k','wear_torque'],
    "air_temperature_k" : ['type','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k','wear_torque'],
    #"process_temperature_k" : ['type','air_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k','wear_torque'],
    #"rotational_speed_rpm" : ['type','air_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k','wear_torque'],
    #"torque_nm" : ['type','air_temperature_k','process_temperature_k','rotational_speed_rpm','tool_wear_min','power_w','delta_temp_k','wear_torque'],
    #"tool_wear_min" : ['type','air_temperature_k','process_temperature_k','rotational_speed_rpm','torque_nm','power_w','delta_temp_k','wear_torque'],
    #"power_w" : ['type','air_temperature_k','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','delta_temp_k','wear_torque'],
    #"delta_temp_k" : ['type','air_temperature_k','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','wear_torque'],
    #"wear_torque" : ['type','air_temperature_k','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k'],
    #"temp_air_and_delta" : ['type','process_temperature_k','tool_wear_min','power_w','wear_torque'],
    #"wear_torque_air_temp" : ['type','process_temperature_k','rotational_speed_rpm','torque_nm','tool_wear_min','power_w','delta_temp_k'],
    }


model_hidden_layer_sizes= [
                #(10,),
                #(16,),
                #(10, 5),
                (16, 8),
                #(64, 32, 16),
            #    (128, 64, 32),
                #(256, 64, 16),
            #    (256, 128, 64, 32),
                #(256, 64, 32, 16),
                ]
model_alpha = [
                #0.00001, 
            #    0.001, 
                0.01,
            #    1,
                #10,
                ]
model_learning_rate_init = [
                #0.00001, 
            #    0.001,
                0.01,
                #0.1,
                ]
model_batch_size = [
                "auto", 
                16,
            #    64,
            #    256,
                ]
model_activation = [
                'relu', 
            #    'tanh', 
                #'logistic'
                ]
model_solver = [
                'adam', 
                'sgd', 
            #    'lbfgs'
                ]

# try different methods to balance classes
imbalance_approach = {
    "class_weights": [
        #1,
        1.5,
        # 2,
           ], 
    #"resampling": ["SMOTETomek", "ADASYN"]
    }

# try different scalers
scalers = {"power":make_pipeline(PowerTransformer())}#, "robust":make_pipeline(RobustScaler())}#,"standard":make_pipeline(StandardScaler()),"quantile":make_pipeline(QuantileTransformer())}

# define dictionary for result collection
results =  {"excluded_column":[], "imbalanced_approach":[],"imbalanced_input":[],"scaler":[], "learning_rate_init":[],"alpha":[],"batch_size":[],"hidden_layer_sizes":[],"activation":[], "solver":[], "prediction_threshold":[],"duration":[], "f1_score":[]}#,"not null gt":[],"exclude":[],"columns":[]}#, "coefficients":[]}

# calculate number of runs for progress reporting
runs = len(column_selection)*len(imbalance_approach)*len(imbalance_approach["class_weights"])*len(scalers)*len(model_hidden_layer_sizes)*len(model_alpha)*len(model_learning_rate_init)*len(model_batch_size)*len(model_activation)*len(model_solver)
i, total_duration, duration, f1_result=0,0,0,0

for approach_key, approach_item in imbalance_approach.items():
    
    for column_key, cols in column_selection.items():
        
        categorical_feat = categorical_feature
        if categorical_feat[0] not in cols:
            categorical_feat=[]
        df_data = load_data(cols, target)
        
        X_train, X_test, y_train, y_test = split_data(df_data, df_data[target], target=target)
        

        for imbalanced_input in approach_item:
        
            for scaler_key, scaler_value in scalers.items():

                for hidden_layer_sizes in model_hidden_layer_sizes:
                    for alpha in model_alpha:
                        for learning_rate_init in model_learning_rate_init:
                            for batch_size in model_batch_size:
                                for activation in model_activation:
                                    for solver in model_solver:

                                        # report progress and remaining computation time
                                        
                                        print(report_progress(runs, i, duration, total_duration, f1_result))
                                        
                                        i +=1
                                        start_time = time.time()

                                        model, parameters = train_with_aggressive_weights(X_train, y_train, scaler_value,approach_key, imbalanced_input, categorical_feat, hidden_layer_sizes, alpha,learning_rate_init, batch_size, activation, solver)

                                        best_threshold = optimize_threshold(model, X_train, y_train)
                                        y_pred = predict_with_threshold(model,X_test,best_threshold)
                                        end_time = time.time()
                                        duration = round(end_time-start_time,0)
                                        total_duration = total_duration + duration
                                        f1_run = round(f1_score(y_test, y_pred)*100,0)
                                        if f1_run > f1_result:
                                            f1_result = f1_run
                                        # collect result
                                        results['excluded_column'].append(column_key)
                                        results['imbalanced_approach'].append(approach_key)
                                        results['imbalanced_input'].append(imbalanced_input)
                                        results['scaler'].append(scaler_key)
                                        results['learning_rate_init'].append(parameters['model__learning_rate_init'])
                                        results['alpha'].append(parameters['model__alpha'])
                                        results['batch_size'].append(parameters['model__batch_size'])
                                        results['hidden_layer_sizes'].append(parameters['model__hidden_layer_sizes'])
                                        results['activation'].append(parameters['model__activation'])
                                        results['solver'].append(parameters['model__solver'])
                                        results['prediction_threshold'].append(best_threshold)
                                        results['f1_score'].append(f1_run)
                                        results['duration'].append(duration)
            

print(report_progress(runs, i, duration, total_duration, f1_result))
#results.to_csv("results_detailed_run.csv")

process with 12 runs started at Fri Dec  5 12:48:20 2025
progress: 8.3%  |  remaining: 0.2min   |  elapsed: 0.0min  |   loop duration: 0.0min    |   best f1: 46.0
progress: 16.7%  |  remaining: 0.2min   |  elapsed: 0.1min  |   loop duration: 0.0min    |   best f1: 59.0
progress: 25.0%  |  remaining: 0.4min   |  elapsed: 0.1min  |   loop duration: 0.1min    |   best f1: 61.0
progress: 33.3%  |  remaining: 1.0min   |  elapsed: 0.5min  |   loop duration: 0.3min    |   best f1: 71.0
progress: 41.7%  |  remaining: 0.7min   |  elapsed: 0.5min  |   loop duration: 0.0min    |   best f1: 71.0
progress: 50.0%  |  remaining: 0.5min   |  elapsed: 0.5min  |   loop duration: 0.0min    |   best f1: 71.0
progress: 58.3%  |  remaining: 0.5min   |  elapsed: 0.7min  |   loop duration: 0.2min    |   best f1: 71.0
progress: 66.7%  |  remaining: 0.5min   |  elapsed: 1.1min  |   loop duration: 0.3min    |   best f1: 73.0
progress: 75.0%  |  remaining: 0.4min   |  elapsed: 1.1min  |   loop duration: 0.0min    |   best f1: 73.0
progress: 83.3%  |  remaining: 0.2min   |  elapsed: 1.1min  |   loop duration: 0.0min    |   best f1: 73.0
progress: 91.7%  |  remaining: 0.1min   |  elapsed: 1.2min  |   loop duration: 0.1min    |   best f1: 73.0
process with 12 runs completed in 1.5min at Fri Dec  5 12:49:50 2025

In [19]:
#results=pd.DataFrame(results)
pd.DataFrame(results).sort_values("f1_score",ascending=False)
#results.to_csv("results_detailed_run.csv")

,excluded_column,imbalanced_approach,imbalanced_input,scaler,learning_rate_init,alpha,batch_size,hidden_layer_sizes,activation,solver,prediction_threshold,duration,f1_score
5,rem,class_weights,1.5,power,0.01,0.01,16,"(16, 8)",relu,sgd,0.85,21.0,73.0
1,none,class_weights,1.5,power,0.01,0.01,16,"(16, 8)",relu,sgd,0.84,21.0,71.0
6,rem,class_weights,1.5,power,0.01,1.00,auto,"(16, 8)",relu,sgd,0.79,2.0,60.0
0,none,class_weights,1.5,power,0.01,0.01,auto,"(16, 8)",relu,sgd,0.89,2.0,59.0
4,rem,class_weights,1.5,power,0.01,0.01,auto,"(16, 8)",relu,sgd,0.82,2.0,59.0
2,none,class_weights,1.5,power,0.01,1.00,auto,"(16, 8)",relu,sgd,0.83,2.0,56.0
7,rem,class_weights,1.5,power,0.01,1.00,16,"(16, 8)",relu,sgd,0.60,20.0,44.0
3,none,class_weights,1.5,power,0.01,1.00,16,"(16, 8)",relu,sgd,0.73,14.0,41.0

In [11]:
# Set options to display all rows and columns
#print(results)
#results=pd.DataFrame(results)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 0)

results.sort_values("f1_score",ascending=False)

           excluded_column imbalanced_approach imbalanced_input scaler  \
1567  wear_torque_air_temp  class_weights       1.5              power
1315  wear_torque_air_temp  class_weights       1                power
1531  wear_torque_air_temp  class_weights       1.5              power
1260  none                  class_weights       1.5              power
1638  wear_torque_air_temp  class_weights       1.5              power
1138  none                  class_weights       1.5              power
594   wear_torque_air_temp  resampling          SMOTETomek       power
1213  none                  class_weights       1.5              power
1476  wear_torque_air_temp  class_weights       1                power
996   none                  class_weights       1                power
1351  wear_torque_air_temp  class_weights       1                power
883   none                  class_weights       1                power
492   wear_torque_air_temp  resampling          SMOTETomek       power
198   none                  resampling          SMOTETomek       power
630   wear_torque_air_temp  resampling          SMOTETomek       power
936   none                  class_weights       1                power
631   wear_torque_air_temp  resampling          SMOTETomek       power
1296  wear_torque_air_temp  class_weights       1                power
1386  wear_torque_air_temp  class_weights       1                power
1396  wear_torque_air_temp  class_weights       1                power
1152  none                  class_weights       1.5              power
1711  wear_torque_air_temp  class_weights       1.5              power
967   none                  class_weights       1                power
1099  none                  class_weights       1.5              power
997   none                  class_weights       1                power
937   none                  class_weights       1                power
1135  none                  class_weights       1.5              power
73    none                  resampling          SMOTETomek       power
1261  none                  class_weights       1.5              power
1189  none                  class_weights       1.5              power
90    none                  resampling          SMOTETomek       power
415   none                  resampling          ADASYN           power
474   wear_torque_air_temp  resampling          SMOTETomek       power
690   wear_torque_air_temp  resampling          ADASYN           power
639   wear_torque_air_temp  resampling          SMOTETomek       power
922   none                  class_weights       1                power
919   none                  class_weights       1                power
703   wear_torque_air_temp  resampling          ADASYN           power
1003  none                  class_weights       1                power
1044  none                  class_weights       1                power
126   none                  resampling          SMOTETomek       power
463   wear_torque_air_temp  resampling          SMOTETomek       power
432   wear_torque_air_temp  resampling          SMOTETomek       power
451   wear_torque_air_temp  resampling          SMOTETomek       power
438   wear_torque_air_temp  resampling          SMOTETomek       power
420   none                  resampling          ADASYN           power
487   wear_torque_air_temp  resampling          SMOTETomek       power
1642  wear_torque_air_temp  class_weights       1.5              power
1432  wear_torque_air_temp  class_weights       1                power
1566  wear_torque_air_temp  class_weights       1.5              power
18    none                  resampling          SMOTETomek       power
918   none                  class_weights       1                power
1050  none                  class_weights       1                power
828   wear_torque_air_temp  resampling          ADASYN           power
1353  wear_torque_air_temp  class_weights       1                power
1188  none                  class_weights       1.5              power
109   none                  resampling          SMOTETomek       power
91    none                  resampling          SMOTETomek       power
1377  wear_torque_air_temp  class_weights       1                power
1584  wear_torque_air_temp  class_weights       1.5              power
1580  wear_torque_air_temp  class_weights       1.5              power
1574  wear_torque_air_temp  class_weights       1.5              power
1603  wear_torque_air_temp  class_weights       1.5              power
1697  wear_torque_air_temp  class_weights       1.5              power
1703  wear_torque_air_temp  class_weights       1.5              power
1709  wear_torque_air_temp  class_weights       1.5              power
1568  wear_torque_air_temp  class_weights       1.5              power
1440  wear_torque_air_temp  class_weights       1                power
1512  wear_torque_air_temp  class_weights       1.5              power
1556  wear_torque_air_temp  class_weights       1.5              power
1562  wear_torque_air_temp  class_weights       1.5              power
58    none                  resampling          SMOTETomek       power
54    none                  resampling          SMOTETomek       power
1225  none                  class_weights       1.5              power
1550  wear_torque_air_temp  class_weights       1.5              power
1192  none                  class_weights       1.5              power
163   none                  resampling          SMOTETomek       power
637   wear_torque_air_temp  resampling          SMOTETomek       power
522   wear_torque_air_temp  resampling          SMOTETomek       power
180   none                  resampling          SMOTETomek       power
181   none                  resampling          SMOTETomek       power
499   wear_torque_air_temp  resampling          SMOTETomek       power
495   wear_torque_air_temp  resampling          SMOTETomek       power
1066  none                  class_weights       1                power
133   none                  resampling          SMOTETomek       power
943   none                  class_weights       1                power
775   wear_torque_air_temp  resampling          ADASYN           power
127   none                  resampling          SMOTETomek       power
1032  none                  class_weights       1                power
97    none                  resampling          SMOTETomek       power
810   wear_torque_air_temp  resampling          ADASYN           power
129   none                  resampling          SMOTETomek       power
270   none                  resampling          ADASYN           power
1721  wear_torque_air_temp  class_weights       1.5              power
1727  wear_torque_air_temp  class_weights       1.5              power
343   none                  resampling          ADASYN           power
1715  wear_torque_air_temp  class_weights       1.5              power
489   wear_torque_air_temp  resampling          SMOTETomek       power
493   wear_torque_air_temp  resampling          SMOTETomek       power
12    none                  resampling          SMOTETomek       power
294   none                  resampling          ADASYN           power
349   none                  resampling          ADASYN           power
199   none                  resampling          SMOTETomek       power
961   none                  class_weights       1                power
121   none                  resampling          SMOTETomek       power
1068  none                  class_weights       1                power
169   none                  resampling          SMOTETomek       power
103   none                  resampling          SMOTETomek       power
613   wear_torque_air_temp  resampling          SMOTETomek       power
691   wear_torque_air_temp  resampling          ADASYN           power
745   wear_torque_air_temp  resampling          ADASYN           power
1224  none                  class_weights       1.5              power
1176  none                  class_weights       1.5              power
1332  wear_torque_air_temp  class_weights       1                power
85    none                  resampling          SMOTETomek       power
1570  wear_torque_air_temp  class_weights       1.5              power
36    none                  resampling          SMOTETomek       power
30    none                  resampling          SMOTETomek       power
24    none                  resampling          SMOTETomek       power
1542  wear_torque_air_temp  class_weights       1.5              power
1200  none                  class_weights       1.5              power
1354  wear_torque_air_temp  class_weights       1                power
205   none                  resampling          SMOTETomek       power
540   wear_torque_air_temp  resampling          SMOTETomek       power
378   none                  resampling          ADASYN           power
553   wear_torque_air_temp  resampling          SMOTETomek       power
568   wear_torque_air_temp  resampling          SMOTETomek       power
187   none                  resampling          SMOTETomek       power
517   wear_torque_air_temp  resampling          SMOTETomek       power
184   none                  resampling          SMOTETomek       power
559   wear_torque_air_temp  resampling          SMOTETomek       power
846   wear_torque_air_temp  resampling          ADASYN           power
847   wear_torque_air_temp  resampling          ADASYN           power
139   none                  resampling          SMOTETomek       power
135   none                  resampling          SMOTETomek       power
1433  wear_torque_air_temp  class_weights       1                power
1436  wear_torque_air_temp  class_weights       1                power
1439  wear_torque_air_temp  class_weights       1                power
1444  wear_torque_air_temp  class_weights       1                power
79    none                  resampling          SMOTETomek       power
1648  wear_torque_air_temp  class_weights       1.5              power
1602  wear_torque_air_temp  class_weights       1.5              power
39    none                  resampling          SMOTETomek       power
63    none                  resampling          SMOTETomek       power
1424  wear_torque_air_temp  class_weights       1                power
1430  wear_torque_air_temp  class_weights       1                power
1427  wear_torque_air_temp  class_weights       1                power
108   none                  resampling          SMOTETomek       power
1159  none                  class_weights       1.5              power
1158  none                  class_weights       1.5              power
1153  none                  class_weights       1.5              power
1320  wear_torque_air_temp  class_weights       1                power
1326  wear_torque_air_temp  class_weights       1                power
1314  wear_torque_air_temp  class_weights       1                power
1233  none                  class_weights       1.5              power
1418  wear_torque_air_temp  class_weights       1                power
1421  wear_torque_air_temp  class_weights       1                power
1415  wear_torque_air_temp  class_weights       1                power
1412  wear_torque_air_temp  class_weights       1                power
1406  wear_torque_air_temp  class_weights       1                power
1409  wear_torque_air_temp  class_weights       1                power
1392  wear_torque_air_temp  class_weights       1                power
1518  wear_torque_air_temp  class_weights       1.5              power
978   none                  class_weights       1                power
960   none                  class_weights       1                power
117   none                  resampling          SMOTETomek       power
1053  none                  class_weights       1                power
705   wear_torque_air_temp  resampling          ADASYN           power
834   wear_torque_air_temp  resampling          ADASYN           power
772   wear_torque_air_temp  resampling          ADASYN           power
762   wear_torque_air_temp  resampling          ADASYN           power
817   wear_torque_air_temp  resampling          ADASYN           power
865   none                  class_weights       1                power
853   wear_torque_air_temp  resampling          ADASYN           power
115   none                  resampling          SMOTETomek       power
123   none                  resampling          SMOTETomek       power
964   none                  class_weights       1                power
942   none                  class_weights       1                power
930   none                  class_weights       1                power
612   wear_torque_air_temp  resampling          SMOTETomek       power
634   wear_torque_air_temp  resampling          SMOTETomek       power
666   wear_torque_air_temp  resampling          ADASYN           power
654   wear_torque_air_temp  resampling          ADASYN           power
555   wear_torque_air_temp  resampling          SMOTETomek       power
589   wear_torque_air_temp  resampling          SMOTETomek       power
600   wear_torque_air_temp  resampling          SMOTETomek       power
523   wear_torque_air_temp  resampling          SMOTETomek       power
563   wear_torque_air_temp  resampling          SMOTETomek       power
569   wear_torque_air_temp  resampling          SMOTETomek       power
575   wear_torque_air_temp  resampling          SMOTETomek       power
557   wear_torque_air_temp  resampling          SMOTETomek       power
545   wear_torque_air_temp  resampling          SMOTETomek       power
551   wear_torque_air_temp  resampling          SMOTETomek       power
186   none                  resampling          SMOTETomek       power
162   none                  resampling          SMOTETomek       power
498   wear_torque_air_temp  resampling          SMOTETomek       power
531   wear_torque_air_temp  resampling          SMOTETomek       power
528   wear_torque_air_temp  resampling          SMOTETomek       power
433   wear_torque_air_temp  resampling          SMOTETomek       power
192   none                  resampling          SMOTETomek       power
486   wear_torque_air_temp  resampling          SMOTETomek       power
462   wear_torque_air_temp  resampling          SMOTETomek       power
196   none                  resampling          SMOTETomek       power
213   none                  resampling          SMOTETomek       power
324   none                  resampling          ADASYN           power
375   none                  resampling          ADASYN           power
361   none                  resampling          ADASYN           power
397   none                  resampling          ADASYN           power
325   none                  resampling          ADASYN           power
288   none                  resampling          ADASYN           power
318   none                  resampling          ADASYN           power
1691  wear_torque_air_temp  class_weights       1.5              power
1685  wear_torque_air_temp  class_weights       1.5              power
1673  wear_torque_air_temp  class_weights       1.5              power
1679  wear_torque_air_temp  class_weights       1.5              power
1656  wear_torque_air_temp  class_weights       1.5              power
1644  wear_torque_air_temp  class_weights       1.5              power
1661  wear_torque_air_temp  class_weights       1.5              power
1667  wear_torque_air_temp  class_weights       1.5              power
1548  wear_torque_air_temp  class_weights       1.5              power
1554  wear_torque_air_temp  class_weights       1.5              power
1585  wear_torque_air_temp  class_weights       1.5              power
1608  wear_torque_air_temp  class_weights       1.5              power
45    none                  resampling          SMOTETomek       power
1446  wear_torque_air_temp  class_weights       1                power
274   none                  resampling          ADASYN           power
1437  wear_torque_air_temp  class_weights       1                power
1462  wear_torque_air_temp  class_weights       1                power
1499  wear_torque_air_temp  class_weights       1                power
1481  wear_torque_air_temp  class_weights       1                power
1487  wear_torque_air_temp  class_weights       1                power
1480  wear_torque_air_temp  class_weights       1                power
1493  wear_torque_air_temp  class_weights       1                power
1505  wear_torque_air_temp  class_weights       1                power
1511  wear_torque_air_temp  class_weights       1                power
88    none                  resampling          SMOTETomek       power
84    none                  resampling          SMOTETomek       power
1195  none                  class_weights       1.5              power
1212  none                  class_weights       1.5              power
1177  none                  class_weights       1.5              power
111   none                  resampling          SMOTETomek       power
1183  none                  class_weights       1.5              power
1405  wear_torque_air_temp  class_weights       1                power
1156  none                  class_weights       1.5              power
1344  wear_torque_air_temp  class_weights       1                power
289   none                  resampling          ADASYN           power
51    none                  resampling          SMOTETomek       power
174   none                  resampling          SMOTETomek       power
160   none                  resampling          SMOTETomek       power
615   wear_torque_air_temp  resampling          SMOTETomek       power
624   wear_torque_air_temp  resampling          SMOTETomek       power
469   wear_torque_air_temp  resampling          SMOTETomek       power
472   wear_torque_air_temp  resampling          SMOTETomek       power
450   wear_torque_air_temp  resampling          SMOTETomek       power
457   wear_torque_air_temp  resampling          SMOTETomek       power
1692  wear_torque_air_temp  class_weights       1.5              power
25    none                  resampling          SMOTETomek       power
421   none                  resampling          ADASYN           power
426   none                  resampling          ADASYN           power
0     none                  resampling          SMOTETomek       power
210   none                  resampling          SMOTETomek       power
490   wear_torque_air_temp  resampling          SMOTETomek       power
211   none                  resampling          SMOTETomek       power
544   wear_torque_air_temp  resampling          SMOTETomek       power
552   wear_torque_air_temp  resampling          SMOTETomek       power
558   wear_torque_air_temp  resampling          SMOTETomek       power
370   none                  resampling          ADASYN           power
881   none                  class_weights       1                power
875   none                  class_weights       1                power
869   none                  class_weights       1                power
855   wear_torque_air_temp  resampling          ADASYN           power
852   wear_torque_air_temp  resampling          ADASYN           power
829   wear_torque_air_temp  resampling          ADASYN           power
816   wear_torque_air_temp  resampling          ADASYN           power
804   wear_torque_air_temp  resampling          ADASYN           power
360   none                  resampling          ADASYN           power
364   none                  resampling          ADASYN           power
787   wear_torque_air_temp  resampling          ADASYN           power
766   wear_torque_air_temp  resampling          ADASYN           power
154   none                  resampling          SMOTETomek       power

In [12]:
old_res = pd.read_csv("results_loop.csv")
old_res.sort_values("f1_score",ascending=False)

,Unnamed: 0,excluded_column,imbalanced_approach,imbalanced_input,scaler,best_learning_rate_init,best_alpha,best_batch_size,best_hidden_layer_sizes,best_activation,best_solver,prediction_threshold,duration,f1_score
24,24,rotational_speed_rpm,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,30.0,77.0
18,18,process_temperature_k,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,30.0,77.0
73,73,type,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.69,9.0,76.0
79,79,air_temperature_k,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,11.0,76.0
78,78,air_temperature_k,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.83,12.0,76.0
22,22,process_temperature_k,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,43.0,75.0
28,28,rotational_speed_rpm,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,41.0,75.0
94,94,rotational_speed_rpm,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,10.0,73.0
101,101,torque_nm,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,11.0,73.0
88,88,process_temperature_k,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,10.0,73.0
91,91,rotational_speed_rpm,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,11.0,73.0
85,85,process_temperature_k,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,11.0,73.0
115,115,delta_temp_k,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,12.0,72.0
111,111,power_w,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,13.0,72.0
121,121,wear_torque,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,9.0,72.0
76,76,type,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,13.0,72.0
75,75,type,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,12.0,72.0
84,84,process_temperature_k,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,12.0,72.0
90,90,rotational_speed_rpm,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,12.0,72.0
68,68,none,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,16.0,71.0
123,123,wear_torque,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,7.0,71.0
110,110,power_w,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,9.0,71.0
74,74,type,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,13.0,71.0
86,86,process_temperature_k,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,15.0,70.0
103,103,tool_wear_min,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.85,7.0,70.0
125,125,wear_torque,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,7.0,70.0
92,92,rotational_speed_rpm,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,15.0,70.0
26,26,rotational_speed_rpm,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,20.0,70.0
20,20,process_temperature_k,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,20.0,70.0
47,47,power_w,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,29.0,70.0
108,108,power_w,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,9.0,70.0
102,102,tool_wear_min,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,12.0,70.0
109,109,power_w,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,9.0,70.0
7,7,type,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,27.0,70.0
14,14,air_temperature_k,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,33.0,70.0
10,10,type,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,31.0,70.0
67,67,none,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.79,12.0,69.0
11,11,type,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.83,21.0,69.0
81,81,air_temperature_k,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,11.0,69.0
107,107,tool_wear_min,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,7.0,69.0
117,117,delta_temp_k,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,7.0,69.0
105,105,tool_wear_min,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,7.0,69.0
119,119,delta_temp_k,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.83,7.0,68.0
71,71,none,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,10.0,68.0
51,51,delta_temp_k,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,31.0,68.0
59,59,wear_torque,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,23.0,68.0
25,25,rotational_speed_rpm,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,34.0,68.0
27,27,rotational_speed_rpm,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,16.0,68.0
21,21,process_temperature_k,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,16.0,68.0
19,19,process_temperature_k,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,34.0,68.0
54,54,wear_torque,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,23.0,67.0
3,3,none,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.71,24.0,67.0
35,35,torque_nm,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.82,24.0,67.0
98,98,torque_nm,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.84,8.0,67.0
77,77,type,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,14.0,67.0
55,55,wear_torque,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,20.0,67.0
43,43,power_w,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,42.0,67.0
37,37,tool_wear_min,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,27.0,67.0
13,13,air_temperature_k,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.77,18.0,67.0
66,66,none,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.85,10.0,67.0
72,72,type,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.82,7.0,67.0
29,29,rotational_speed_rpm,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.85,33.0,66.0
1,1,none,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,42.0,66.0
41,41,tool_wear_min,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,26.0,66.0
16,16,air_temperature_k,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,35.0,66.0
17,17,air_temperature_k,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,23.0,66.0
30,30,torque_nm,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,24.0,66.0
23,23,process_temperature_k,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.85,34.0,66.0
45,45,power_w,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,31.0,66.0
95,95,rotational_speed_rpm,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,14.0,66.0
53,53,delta_temp_k,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,35.0,66.0
97,97,torque_nm,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,12.0,66.0
89,89,process_temperature_k,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,14.0,66.0
39,39,tool_wear_min,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,54.0,66.0
36,36,tool_wear_min,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.71,29.0,66.0
33,33,torque_nm,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,29.0,65.0
34,34,torque_nm,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.76,24.0,65.0
70,70,none,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,8.0,65.0
112,112,power_w,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,8.0,65.0
104,104,tool_wear_min,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,13.0,65.0
69,69,none,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,8.0,65.0
124,124,wear_torque,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.80,7.0,65.0
106,106,tool_wear_min,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,8.0,65.0
87,87,process_temperature_k,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,12.0,65.0
93,93,rotational_speed_rpm,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,12.0,65.0
96,96,torque_nm,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,8.0,65.0
5,5,none,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,22.0,65.0
6,6,type,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,25.0,65.0
9,9,type,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,35.0,65.0
49,49,delta_temp_k,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,32.0,65.0
8,8,type,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,27.0,65.0
15,15,air_temperature_k,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,28.0,65.0
122,122,wear_torque,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,8.0,64.0
0,0,none,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.79,36.0,64.0
38,38,tool_wear_min,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.84,21.0,64.0
58,58,wear_torque,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,30.0,64.0
32,32,torque_nm,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,18.0,64.0
4,4,none,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.82,31.0,64.0
57,57,wear_torque,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,20.0,64.0
80,80,air_temperature_k,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.82,7.0,64.0
120,120,wear_torque,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,8.0,64.0
46,46,power_w,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.78,21.0,63.0
82,82,air_temperature_k,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,7.0,63.0
113,113,power_w,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,7.0,63.0
42,42,power_w,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,18.0,63.0
40,40,tool_wear_min,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.85,49.0,63.0
31,31,torque_nm,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,34.0,63.0
44,44,power_w,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,32.0,63.0
56,56,wear_torque,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.75,31.0,62.0
99,99,torque_nm,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,12.0,61.0
12,12,air_temperature_k,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,32.0,61.0
100,100,torque_nm,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,11.0,60.0
83,83,air_temperature_k,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,18.0,59.0
2,2,none,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,25.0,58.0
128,128,temp_air_and_delta,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,9.0,53.0
114,114,delta_temp_k,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.81,8.0,51.0
129,129,temp_air_and_delta,class_weights,1.5,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,11.0,51.0
131,131,temp_air_and_delta,class_weights,1.75,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.84,10.0,50.0
127,127,temp_air_and_delta,class_weights,1.25,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,11.0,50.0
126,126,temp_air_and_delta,class_weights,1.25,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.86,9.0,50.0
116,116,delta_temp_k,class_weights,1.5,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,10.0,49.0
130,130,temp_air_and_delta,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,7.0,48.0
61,61,temp_air_and_delta,resampling,SMOTE,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,36.0,46.0
63,63,temp_air_and_delta,resampling,ADASYN,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,39.0,45.0
62,62,temp_air_and_delta,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,24.0,45.0
52,52,delta_temp_k,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,38.0,44.0
64,64,temp_air_and_delta,resampling,SMOTETomek,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.88,37.0,43.0
65,65,temp_air_and_delta,resampling,SMOTETomek,robust,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.85,33.0,42.0
48,48,delta_temp_k,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,18.0,42.0
50,50,delta_temp_k,resampling,ADASYN,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.89,54.0,41.0
118,118,delta_temp_k,class_weights,1.75,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.84,8.0,40.0
60,60,temp_air_and_delta,resampling,SMOTE,power,0.001,0.001,16,"(128, 64, 32)",relu,adam,0.87,44.0,39.0

In [ ]:
    grid_random_search=True
    
if grid_random_search == True:
        mlp = MLPClassifier(
            learning_rate='adaptive',
            max_iter=1500,
            early_stopping=True,
            validation_fraction=0.15,
            n_iter_no_change=30,
            random_state=42,
            verbose=False
            )
        param_grid = {
            'model__hidden_layer_sizes': [
                #(10,),
                #(16,),
                #(10, 5),
                #(16, 8),
                #(64, 32, 16),
                (128, 64, 32),
                (256, 64, 16),
                (64, 32, 16, 8),
                #(256, 64, 32, 16),
                ],
            'model__alpha': [
                #0.00001, 
                0.001, 
                0.01,
                #1,
                #10,
                ],
            'model__learning_rate_init': [
                #0.00001, 
                #0.001,
                0.01,
                #0.1,
                ],
            'model__batch_size': [
                #"auto", 
                16,
                64,
                256,
                ],
            'model__activation': [
                'relu', 
                'tanh', 
                #'logistic'
                ],
            'model__solver': [
                'adam', 
                'sgd', 
                'lbfgs'
                ],
        }

f1_scorer = make_scorer(f1_score, pos_label=minority_class)

        if grid_random_search == True:
        model = GridSearchCV(        #RandomizedSearchCV(
            pipeline,
            param_grid,
            cv=StratifiedKFold(n_splits=5),
            scoring=f1_scorer,
            n_jobs=-1,
            verbose=1
        )
    else:

if grid_random_search == True:
        best_model=model.best_estimator_
        best_params = model.best_params_
    else: